### ISSUE TITLE
Run tests on CI

### ISSUE THREAD

**Issue by 64J0** [TheAlgorithms/F-Sharp#25]
Just to know, what do you think about running the automated tests on CI?

I can create a PR adding this feature if you'd like.

**Comment by mertcandav** [comment]
Sounds good! Your PR will be merged.

**Comment by 64J0** [comment]
When running the tests locally I actually got some errors. The logs:

```bash
Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
  Failed assembleTransformation (abbbaba,abbba) [22 ms]
  Error Message:
   Test method Algorithms.Tests.Strings.MinCostStringConversionTests.assembleTransformation threw exception: 
System.Reflection.TargetParameterCountException: Parameter count mismatch.
  Stack Trace:
      at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.ThreadOperations.ExecuteWithAbortSafety(Action action)

  Failed assembleTransformation (ababa,ababa) [< 1 ms]
  Error Message:
   Test method Algorithms.Tests.Strings.MinCostStringConversionTests.assembleTransformation threw exception: 
System.Reflection.TargetParameterCountException: Parameter count mismatch.
  Stack Trace:
      at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.ThreadOperations.ExecuteWithAbortSafety(Action action)


Failed!  - Failed:     2, Passed:   176, Skipped:     0, Total:   178, Duration: 315 ms - Algorithms.Tests.dll (net6.0)
```
